apiVersion: v1
kind: Pod
metadata:
  name: access-pv
spec:
  containers:
  - name: access-volumes
    image: pymonger/calrissian:latest
    command: ["sleep", "infinity"]
    volumeMounts:
      - mountPath: /calrissian/tmpout
        name: calrissian-tmpout
      - mountPath: /calrissian/output-data
        name: calrissian-output-data
  volumes:
  - name: calrissian-tmpout
    persistentVolumeClaim:
      claimName: calrissian-tmpout
  - name: calrissian-output-data
    persistentVolumeClaim:
      claimName: calrissian-output-data
