kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: my-azurefile
provisioner: file.csi.azure.com # replace with "kubernetes.io/azure-file" if aks version is less than 1.21
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  # azurefile storageclass specifies 0 for uid and gid but that will cause
  # papermill and ipython to croak because of permissions issues. With this
  # custom storageclass we set the uid/gid mount options to that of the user
  # in the pod container spawned by calrissian.
  - uid=1001
  - gid=1001
  - mfsymlinks
  - cache=strict
  - actimeo=30
parameters:
  skuName: Standard_LRS
